name: sharechip_project
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.0.1+1

  flutter_launcher_icons: "^0.10.0"

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/splash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
  - assets/

  fonts:
  - family: InterBold
    fonts:
    - asset: fonts/inter/Inter-Bold.ttf
  
  - family: InterRegular
    fonts:
    - asset: fonts/inter/Inter-Regular.ttf